apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kust-dev
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/hello2ashu-org/flux-practice