apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kust-base
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./tenant/base/
  prune: true
  sourceRef:
    kind: GitRepository
    name: kust-base
  targetNamespace: kust-base