apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata: 
  name: dev
  namespace: kust-base
spec:
  dependsOn:
    - dev
interval: 1h
retryInterval: 1m
timeout: 5m
prune: true
wait: true
sourceRef:
  kind: GitRepository
  name: flux-system  	
path: ./tenant/base